spring:
  profiles:
    group:
      "dev-profile": "jwt"
      "prod-profile": "jwt"
    include: jwt

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 197339973597-npaofqa7ngr8qgpam0d843af928a4v2r.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
            redirect-uri: http://localhost:8080/oauth2/callback/google
          naver:
            client-id: 1LyHxB8skP0Hh68iEa5P
            client-secret: 3rK_ExeIEx
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/naver
          kakao:
            client-id: 66c5ba77d82e4dbed66a1f8fc91f00bd
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
            client-name: Kakao
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  cloud:
    aws:
      credential:
        accessKey: AKIAQO6CUPHGJILCKF2W
        secretKey: 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
      s3:
        bucket: d209-petmily-bucket  # s3 버킷 이름
      region:
        static: ap-northeast-2  # region
        auto: false
      stack:
        auto: false

